version: '3'

volumes:
  mongodb_volume:

services:

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_volume:/data/db
    restart: always

  web:
    build: ./
    restart: always
    ports:
      - 8080:8080
    environment:
      - MONGO_DB_ADDR=mongodb
      - MONGO_DB_PORT=27017
      - MONGODB_DATABASE=forms


